PrimeFaces.locales['fr'] = {
    closeText: 'Fermer',
    prevText: 'Précédent',
    nextText: 'Suivant',
    monthNames: ['Janvier', 'F\xE9vrier', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Ao\xFBt', 'Septembre', 'Octobre', 'Novembre', 'D\xE9cembre' ],
    monthNamesShort: ['Jan', 'F\xE9v', 'Mar', 'Avr', 'Mai', 'Jun', 'Jul', 'Ao\xFB', 'Sep', 'Oct', 'Nov', 'D\xE9c' ],
    dayNames: ['Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi'],
    dayNamesShort: ['Dim', 'Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
    dayNamesMin: ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
    weekHeader: 'Semaine',
    firstDay: 1,
    isRTL: false,
    showMonthAfterYear: false,
    yearSuffix:'',
    timeOnlyTitle: 'Choisir l\'heure',
    timeText: 'Heure',
    hourText: 'Heures',
    minuteText: 'Minutes',
    secondText: 'Secondes',
    currentText: 'Maintenant',
    ampm: false,
    month: 'Mois',
    week: 'Semaine',
    day: 'Jour',
    allDayText: 'Toute la journ\xE9e'
};